spring:
  application:
    name: taskflow
  datasource:
    url: jdbc:postgresql://localhost:5432/taskflow
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true